version: '2'
services:
  # jupyter notebook
  jupyter:
    build: .
    image: kzmake/jupyter-scala:1.0
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    tty: true
    stdin_open: true
    command: start-notebook.sh --NotebookApp.token=''
